### ISSUE TITLE
ERRO[0008] Process insert: sqlite3: constraint failed [1555] pid 739754, lineNo 2626176, rmt-Journal

### ISSUE THREAD

**Issue by angelamorgan** [rcowham/go-libp4dlog#20]
log2sql --version
log2sql, version v0.9.6 (branch: master, revision: 79d33b7)
  build user:       rcowham@perforce.com
  build date:       2021-02-10T17:26:30+0000
  go version:       go1.13.4

log2sql log.2023-10-03_21-57-01
INFO[0000] log2sql, version v0.9.6 (branch: master, revision: 79d33b7)
  build user:       rcowham@perforce.com
  build date:       2021-02-10T17:26:30+0000
  go version:       go1.13.4 
INFO[0000] Starting 2023-10-17 02:14:38.117776154 -0500 CDT m=+0.001867948, Logfiles: [log.2023-10-03_21-57-01] 
INFO[0000] Flags: debug 0, json/file false/, sql/file false/, dbName , noMetrics/file false/ 
INFO[0000]        serverID , sdpInstance , updateInterval 10s, noOutputCmdsByUser false, outputCmdsByUserRegex  caseInsensitve false, debugPID/cmd 0/ 
INFO[0000] Creating metrics output: log.2023-10-03_21-57-01.metrics, config: &{Debug:0 ServerID: SDPInstance: UpdateInterval:10s OutputCmdsByUser:true OutputCmdsByUserRegex: OutputCmdsByIP:true CaseSensitiveServer:true} 
INFO[0000] Creating database: log.2023-10-03_21-57-01.db 
INFO[0000] Processing: log.2023-10-03_21-57-01          
INFO[0000] Progress reporting frequency: 10s            
INFO[0000] Resetting running to 112 as encountered server threads message 
ERRO[0008] Process insert: sqlite3: constraint failed [1555] pid 739754, lineNo 2626176, rmt-Journal 
ERRO[0008] Process insert: sqlite3: constraint failed [1555] pid 739754, lineNo 2630614, rmt-Journal 
log.2023-10-03_21-57-01: 154.1 MB/6.2 GB 2% estimated finish 02:21:21, 6m33s remaining...
ERRO[0016] Process insert: sqlite3: constraint failed [1555] pid 739754, lineNo 5053983, rmt-Journal 
log.2023-10-03_21-57-01: 282.1 MB/6.2 GB 5% estimated finish 02:21:58, 7m0s remaining...
ERRO[0020] Process insert: sqlite3: constraint failed [1555] pid 739754, lineNo 6440422, rmt-Journal 
ERRO[0022] Process insert: sqlite3: constraint failed [1555] pid 739754, lineNo 7075368, rmt-Journal 
ERRO[0025] Process insert: sqlite3: constraint failed [1555] pid 739754, lineNo 7787783, rmt-Journal 
ERRO[0025] Process insert: sqlite3: constraint failed [1555] pid 707082, lineNo 7798311, rmt-Journal 
log.2023-10-03_21-57-01: 407.9 MB/6.2 GB 7% estimated finish 02:22:14, 7m7s remaining...
ERRO[0037] Process insert: sqlite3: constraint failed [1555] pid 707082, lineNo 11498516, rmt-Journal 
log.2023-10-03_21-57-01: 530.6 MB/6.2 GB 9% estimated finish 02:22:26, 7m8s remaining...
ERRO[0042] Process insert: sqlite3: constraint failed [1555] pid 739754, lineNo 12871961, rmt-Journal 
log.2023-10-03_21-57-01: 658.5 MB/6.2 GB 11% estimated finish 02:22:29, 7m2s remaining...
ERRO[0054] Process insert: sqlite3: constraint failed [1555] pid 707082, lineNo 16486321, rmt-Journal 
ERRO[0054] Process insert: sqlite3: constraint failed [1555] pid 739754, lineNo 16489264, rmt-Journal 
log.2023-10-03_21-57-01: 783.3 MB/6.2 GB 13% estimated finish 02:22:33, 6m56s remaining...
log.2023-10-03_21-57-01: 900.7 MB/6.2 GB 15% estimated finish 02:22:40, 6m53s remaining...
log.2023-10-03_21-57-01: 1.0 GB/6.2 GB 16% estimated finish 02:22:45, 6m47s remaining...
ERRO[0083] Process insert: sqlite3: constraint failed [1555] pid 707082, lineNo 24642049, rmt-Journal 
log.2023-10-03_21-57-01: 1.1 GB/6.2 GB 18% estimated finish 02:22:47, 6m39s remaining...
ERRO[0093] Process insert: sqlite3: constraint failed [1555] pid 739754, lineNo 27523330, rmt-Journal 
ERRO[0093] Process insert: sqlite3: constraint failed [1555] pid 707082, lineNo 27555200, rmt-Journal 
log.2023-10-03_21-57-01: 1.3 GB/6.2 GB 20% estimated finish 02:22:48, 6m31s remaining...
ERRO[0106] Process insert: sqlite3: constraint failed [1555] pid 707082, lineNo 31529631, rmt-Journal 
log.2023-10-03_21-57-01: 1.4 GB/6.2 GB 22% estimated finish 02:22:50, 6m22s remaining...
ERRO[0112] Process insert: sqlite3: constraint failed [1555] pid 739754, lineNo 33080072, rmt-Journal 
ERRO[0116] Process insert: sqlite3: constraint failed [1555] pid 739754, lineNo 34375043, rmt-Journal 
ERRO[0116] Process insert: sqlite3: constraint failed [1555] pid 739754, lineNo 34386244, rmt-Journal 
log.2023-10-03_21-57-01: 1.5 GB/6.2 GB 24% estimated finish 02:22:51, 6m13s remaining...
ERRO[0122] Process insert: sqlite3: constraint failed [1555] pid 707082, lineNo 35981535, rmt-Journal 
ERRO[0124] Process insert: sqlite3: constraint failed [1555] pid 739754, lineNo 36787281, rmt-Journal 
log.2023-10-03_21-57-01: 1.6 GB/6.2 GB 26% estimated finish 02:22:52, 6m4s remaining...
log.2023-10-03_21-57-01: 1.8 GB/6.2 GB 28% estimated finish 02:22:54, 5m57s remaining...
ERRO[0140] Process insert: sqlite3: constraint failed [1555] pid 707082, lineNo 41296513, rmt-Journal 
log.2023-10-03_21-57-01: 1.9 GB/6.2 GB 30% estimated finish 02:22:55, 5m48s remaining...
log.2023-10-03_21-57-01: 2.0 GB/6.2 GB 32% estimated finish 02:22:56, 5m38s remaining...
ERRO[0164] Process insert: sqlite3: constraint failed [1555] pid 739754, lineNo 48161895, rmt-Journal 
ERRO[0167] Process insert: sqlite3: constraint failed [1555] pid 707082, lineNo 49041685, rmt-Journal 
log.2023-10-03_21-57-01: 2.1 GB/6.2 GB 34% estimated finish 02:22:57, 5m29s remaining...
log.2023-10-03_21-57-01: 2.2 GB/6.2 GB 36% estimated finish 02:22:57, 5m19s remaining...
ERRO[0183] Process insert: sqlite3: constraint failed [1555] pid 739754, lineNo 53789219, rmt-Journal 
ERRO[0186] Process insert: sqlite3: constraint failed [1555] pid 739754, lineNo 54543568, rmt-Journal 
log.2023-10-03_21-57-01: 2.4 GB/6.2 GB 38% estimated finish 02:22:57, 5m9s remaining...
ERRO[0196] Process insert: sqlite3: constraint failed [1555] pid 739754, lineNo 57507769, rmt-Journal 
log.2023-10-03_21-57-01: 2.5 GB/6.2 GB 40% estimated finish 02:22:57, 4m59s remaining...
log.2023-10-03_21-57-01: 2.6 GB/6.2 GB 42% estimated finish 02:22:59, 4m51s remaining...
log.2023-10-03_21-57-01: 2.7 GB/6.2 GB 44% estimated finish 02:22:59, 4m42s remaining...
log.2023-10-03_21-57-01: 2.9 GB/6.2 GB 46% estimated finish 02:22:59, 4m31s remaining...
log.2023-10-03_21-57-01: 3.0 GB/6.2 GB 48% estimated finish 02:22:59, 4m22s remaining...
log.2023-10-03_21-57-01: 3.1 GB/6.2 GB 50% estimated finish 02:23:00, 4m12s remaining...
log.2023-10-03_21-57-01: 3.2 GB/6.2 GB 52% estimated finish 02:23:00, 4m3s remaining...
ERRO[0263] Process insert: sqlite3: constraint failed [1555] pid 739754, lineNo 76190995, rmt-Journal 
ERRO[0268] Process insert: sqlite3: constraint failed [1555] pid 739754, lineNo 77599638, rmt-Journal 
log.2023-10-03_21-57-01: 3.3 GB/6.2 GB 54% estimated finish 02:23:00, 3m53s remaining...
log.2023-10-03_21-57-01: 3.4 GB/6.2 GB 55% estimated finish 02:23:03, 3m45s remaining...
log.2023-10-03_21-57-01: 3.6 GB/6.2 GB 57% estimated finish 02:23:03, 3m35s remaining...
ERRO[0299] Process insert: sqlite3: constraint failed [1555] pid 3229730, lineNo 86329114, rmt-Journal 
log.2023-10-03_21-57-01: 3.7 GB/6.2 GB 59% estimated finish 02:23:03, 3m25s remaining...
ERRO[0303] Process insert: sqlite3: constraint failed [1555] pid 3229730, lineNo 87596913, rmt-Journal 
log.2023-10-03_21-57-01: 3.8 GB/6.2 GB 61% estimated finish 02:23:02, 3m15s remaining...
log.2023-10-03_21-57-01: 3.9 GB/6.2 GB 63% estimated finish 02:23:03, 3m5s remaining...
log.2023-10-03_21-57-01: 4.1 GB/6.2 GB 65% estimated finish 02:23:03, 2m56s remaining...
log.2023-10-03_21-57-01: 4.2 GB/6.2 GB 67% estimated finish 02:23:03, 2m46s remaining...
log.2023-10-03_21-57-01: 4.3 GB/6.2 GB 69% estimated finish 02:23:04, 2m36s remaining...
ERRO[0358] Process insert: sqlite3: constraint failed [1555] pid 3229730, lineNo 103009175, rmt-Journal 
log.2023-10-03_21-57-01: 4.4 GB/6.2 GB 71% estimated finish 02:23:05, 2m27s remaining...
log.2023-10-03_21-57-01: 4.5 GB/6.2 GB 73% estimated finish 02:23:05, 2m17s remaining...
ERRO[0372] Process insert: sqlite3: constraint failed [1555] pid 707082, lineNo 106869904, rmt-Journal 
ERRO[0372] Process insert: sqlite3: constraint failed [1555] pid 707082, lineNo 106901972, rmt-Journal 
log.2023-10-03_21-57-01: 4.6 GB/6.2 GB 75% estimated finish 02:23:05, 2m8s remaining...
ERRO[0381] Process insert: sqlite3: constraint failed [1555] pid 707082, lineNo 109476303, rmt-Journal 
log.2023-10-03_21-57-01: 4.8 GB/6.2 GB 77% estimated finish 02:23:06, 1m59s remaining...
log.2023-10-03_21-57-01: 4.9 GB/6.2 GB 79% estimated finish 02:23:07, 1m49s remaining...
log.2023-10-03_21-57-01: 5.0 GB/6.2 GB 80% estimated finish 02:23:07, 1m40s remaining...
log.2023-10-03_21-57-01: 5.1 GB/6.2 GB 82% estimated finish 02:23:08, 1m30s remaining...
ERRO[0424] Process insert: sqlite3: constraint failed [1555] pid 739754, lineNo 121325925, rmt-Journal 
ERRO[0428] Process insert: sqlite3: constraint failed [1555] pid 739754, lineNo 122383516, rmt-Journal 
log.2023-10-03_21-57-01: 5.2 GB/6.2 GB 84% estimated finish 02:23:08, 1m20s remaining...
log.2023-10-03_21-57-01: 5.3 GB/6.2 GB 86% estimated finish 02:23:09, 1m11s remaining...
log.2023-10-03_21-57-01: 5.5 GB/6.2 GB 88% estimated finish 02:23:09, 1m2s remaining...
ERRO[0454] Process insert: sqlite3: constraint failed [1555] pid 3229730, lineNo 129553897, rmt-Journal 
log.2023-10-03_21-57-01: 5.6 GB/6.2 GB 90% estimated finish 02:23:09, 52s remaining...
ERRO[0461] Process insert: sqlite3: constraint failed [1555] pid 739754, lineNo 131410145, rmt-Journal 
ERRO[0467] Process insert: sqlite3: constraint failed [1555] pid 3229730, lineNo 133139971, rmt-Journal 
ERRO[0469] Process insert: sqlite3: constraint failed [1555] pid 3229730, lineNo 133851172, rmt-Journal 
log.2023-10-03_21-57-01: 5.7 GB/6.2 GB 92% estimated finish 02:23:10, 42s remaining...
ERRO[0470] Process insert: sqlite3: constraint failed [1555] pid 3229730, lineNo 133920672, rmt-Journal 
ERRO[0479] Process insert: sqlite3: constraint failed [1555] pid 707082, lineNo 136415109, rmt-Journal 
ERRO[0479] Process insert: sqlite3: constraint failed [1555] pid 3229730, lineNo 136421248, rmt-Journal 
log.2023-10-03_21-57-01: 5.8 GB/6.2 GB 94% estimated finish 02:23:11, 33s remaining...
ERRO[0482] Process insert: sqlite3: constraint failed [1555] pid 739754, lineNo 137235473, rmt-Journal 
ERRO[0482] Process insert: sqlite3: constraint failed [1555] pid 707082, lineNo 137240906, rmt-Journal 
ERRO[0488] Process insert: sqlite3: constraint failed [1555] pid 739754, lineNo 139008279, rmt-Journal 
log.2023-10-03_21-57-01: 5.9 GB/6.2 GB 95% estimated finish 02:23:11, 23s remaining...
ERRO[0493] Process insert: sqlite3: constraint failed [1555] pid 3229730, lineNo 140484789, rmt-Journal 
log.2023-10-03_21-57-01: 6.0 GB/6.2 GB 97% estimated finish 02:23:11, 13s remaining...
ERRO[0506] Process insert: sqlite3: constraint failed [1555] pid 3229730, lineNo 144371655, rmt-Journal 
log.2023-10-03_21-57-01: 6.2 GB/6.2 GB 99% estimated finish 02:23:11, 3s remaining...
ERRO[0510] Process insert: sqlite3: constraint failed [1555] pid 707082, lineNo 145448660, rmt-Journal 
INFO[0513] Finished all log files                       
INFO[0513] Main: metrics closed                         
ERRO[0513] Process insert: sqlite3: constraint failed [1555] pid 707082, lineNo 146275118, rmt-Journal 
INFO[0515] Completed 2023-10-17 02:23:13.483724519 -0500 CDT m=+515.367816335, elapsed 8m35.365948439s

**Comment by rcowham** [comment]
Fixed in 7dce8d2900395da0219ea466a7e0dc53b7bdf42c
