### ISSUE TITLE
Add filetotals data to what log2sql can track and query on. 

### ISSUE THREAD

**Issue by sgcommons** [rcowham/go-libp4dlog#21]
2023.2 and later servers add filetotall data. Useful for tracking things like sync performance:

2024/07/11 11:16:51 pid 3433924 bruno@bruno_ws 127.0.0.1 [p4/2023.2/LINUX26X86_64/2605454] 'user-sync -f //depot/data/...'
--- lapse 70.9s
--- usage 16270+5907us 136024+176io 0+0net 15216k 0pf
--- memory cmd/proc 5mb/5mb
--- rpc msgs/size in+out 32+29907/0mb+1863mb himarks 97604/97604 snd/rcv 58.5s/.326s
**--- filetotals (svr) send/recv files+bytes 25+1862mb/0+0mb**

Perforce server info:
    2024/07/11 11:18:02 pid 3433924 unknown@unknown 127.0.0.1 [p4/2023.2/LINUX26X86_64/2605454] 'client-Stats'
**--- filetotals (client) send/recv files+bytes 0+0mb/25+1862mb**

**Comment by rcowham** [comment]
Fixed in 245263d4afaace9f59056273930b3872d54f17a0
